definitions:
  model.BadRequestResponse:
    type: object
  model.CreateRecordRequest:
    properties:
      msg_type:
        type: string
      user:
        type: string
    type: object
  model.CreateRecordResponse:
    properties:
      id:
        type: integer
      msg_type:
        type: string
      user:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/records/:
    post:
      consumes:
      - application/json
      - text/xml
      - application/x-www-form-urlencoded
      parameters:
      - description: Records
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.CreateRecordRequest'
      produces:
      - application/json
      - text/xml
      - application/x-www-form-urlencoded
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.CreateRecordResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.BadRequestResponse'
      summary: Создание новых записей
      tags:
      - records-controller
swagger: "2.0"
